server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: marcos27

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
